export const ADD_ENTRY = 'ADD_ENTRY';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const SAVE_ENTRY_SUCCESS = 'SAVE_ENTRY_SUCCESS';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';
export const SET_CURRENT_ENTRY = 'SET_CURRENT_ENTRY';
export const UNSET_CURRENT_ENTRY = 'UNSET_CURRENT_ENTRY';