export const USER_LOGIN = 'USER_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const UNSET_LOGGED_IN_USER = 'UNSET_LOGGED_IN_USER';
