export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const UNSET_LOGGED_IN_USER = 'UNSET_LOGGED_IN_USER';
